#!/usr/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh

bspc rule -a -o firefox desktop=1
bspc rule -a -o gnome-terminal desktop=2
bspc rule -a -o gimp desktop=6
