#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh

bspc rule -a -o firefox desktop=1
bspc rule -a -o gnome-terminal desktop=2
bspc rule -a -o gimp desktop=6
